Concessionaria/Web/Pastelaria.Web/Controllers/EstoqueController.cs
using Concessionaria.Web.Application.Estoque;
using Concessionaria.Web.Application.Estoque.Model;
using Concessionaria.Web.Application.Modelo;
using Concessionaria.Web.Infra;
using System.Web.Mvc;

namespace Concessionaria.Web.Controllers
{ 
    public class EstoqueController : BaseController
    {

        private readonly EstoqueApplication _estoqueApplication;
        private readonly ModeloApplication _modeloApplication;

        public EstoqueController(EstoqueApplication estoqueApplication, ModeloApplication modeloApplication)
        {
            _estoqueApplication = estoqueApplication;
            _modeloApplication = modeloApplication;
        }


    public ActionResult Index()
        {
            return View();
        }

        public ActionResult ListarEstoque()
        {

            var response = _estoqueApplication.BuscarEstoque();
            return View("_GridEstoques", response.Content);
        }

      
        public ActionResult Adicionar()
        {
            var modelos = _modeloApplication.BuscarModelos().Content;

            return View(new AdicionaEstoqueViewModel
            {
                Modelo = modelos
            });
        }

        [HttpPost]
        public ActionResult Adicionar(EstoqueModel model)
        {
            if (!ModelState.IsValid || model == null)
                return Json(new { success = false, message = "Falha ao adicionar ." });

            _estoqueApplication.Post(model);
            return Json(new { success = true, message = " adicionado com sucesso!" });
        }


        public ActionResult Editar(int id)
        {
            var estoque = _estoqueApplication.BuscarEstoquePorId(id).Content;

            return View("Editar", estoque);
        }

        [HttpPost]
        public ActionResult Editar(EstoqueModel model)
        {
            if (model.Cor == null || model.Placa == null || model.Valor == null || model.Detalhes == null)
                return Json(new { success = false, message = "Falha ao Editar preencher todos os campos." });

            var response = _estoqueApplication.Put(model);

            return Json(new { success = true, message = "Editado com sucesso!" });
        }




        public ActionResult Excluir(int id)
        {
            _estoqueApplication.Delete(id);
            return Json(new { success = true, message = "Modelo excluída com sucesso!" });
        }



        public ActionResult Detalhes()
        {
            return View();
        }

    }
}

Concessionaria/Web/Pastelaria.Web/Controllers/MarcaController.cs
using Concessionaria.Web.Application.Marca;
using Concessionaria.Web.Application.Marca.Model;
using System.Web.Mvc;
using Concessionaria.Web.Infra;
using Concessionaria.Web.Application.Modelo;

namespace Concessionaria.Web.Controllers
{
    public class MarcaController : BaseController
    {
        // Instâncias das aplicações e serviços injetados no controlador
        private readonly MarcaApplication _marcaApplication;
   

        public MarcaController(MarcaApplication marcaApplication)  // Construtor que recebe o serviço `MarcaApplication` como dependência.
        {
            _marcaApplication = marcaApplication;  // Inicializa a variável `_marcaApplication` com a instância recebida.
        }

        // GET: Marca
        public ActionResult Index()                 // Método responsável por exibir a página inicial (listagem ou grid) de Marcas.
        {
            return View();                          // Retorna a View padrão associada à ação `Index`.
        }

        public ActionResult ListarMarcas()          // Método para listar as marcas cadastradas.
        {
            var response = _marcaApplication.BuscarMarcas();
            return View("_GridMarcas", response.Content);
        }

        public ActionResult Adicionar()
        {

            return View();
        }

        [HttpPost]
        public ActionResult Adicionar(MarcaModel model)
        {

            var marcasExistentes = _marcaApplication.BuscarMarcas();

            // Passo 2: Verificar se a nova marca já existe
            foreach (var marca in marcasExistentes.Content)
            {
                if (marca.Marca == model.Marca)  // Verifica se o nome da marca é igual ao nome da nova marca
                {
                    // Se a marca já existir, retorna um JSON informando o erro
                    return Json(new { success = false, message = "A marca já existe." });
                }
            }
            if (model.Marca == null)
            {
                return Json(new { success = false, message = "A marca não pode estar vazia." });
            }

            if (ModelState.IsValid)
            {
                // Chama o método para adicionar a marca via `MarcaApplication`
                var response = _marcaApplication.Post(model);

               
                {
                    // Retorna um JSON indicando sucesso
                    return Json(new { success = true, message = "Marca adicionada com sucesso!" });
                  
                }
            }

            // Retorna um JSON indicando falha
            return Json(new { success = false, message = "Falha ao adicionar marca." });
        }

        // Método para carregar os dados da marca para edição
        public ActionResult Editar(int id)
        {

            var response = _marcaApplication.BuscarMarcaPorId(id); // Método para buscar a marca pelo ID
            return View(response.Content); // Retorna a View para editar a marca
        }

        [HttpPost]
        public ActionResult Editar(MarcaModel model)
        {

            var marcasExistentes = _marcaApplication.BuscarMarcas();

            // Passo 2: Verificar se a nova marca já existe
            foreach (var marca in marcasExistentes.Content)
            {
                if (marca.Marca == model.Marca)  // Verifica se o nome da marca é igual ao nome da nova marca
                {
                    // Se a marca já existir, retorna um JSON informando o erro
                    return Json(new { success = false, message = "A marca já existe nao pode ser editada." });
                }
            }

            if (model.Marca == null) {
                return Json(new { success = false, message = "A marca não pode estar vazia." });
            }
            if (ModelState.IsValid)
            {
                var response = _marcaApplication.Put(model); // Método para atualizar a marca
                return Json(new { success = true, message = "Marca atualizada com sucesso!" });
            }

            return Json(new { success = false, message = "Falha ao atualizar a marca." });
        }

        public ActionResult Excluir(int id)
        {
            // Valida se a marca está associada a algum modelo
            var validacaoResponse = _marcaApplication.ValidarMarcaEmodelo(id).Content;

            // Se o valor retornado for 0, significa que a marca não está associada a nenhum modelo
            if (validacaoResponse == false)
            {
                // Tenta excluir a marca
                var response = _marcaApplication.Delete(id); // Supondo que Delete retorne Response<bool>

                // Acessa o conteúdo da resposta para verificar o sucesso da exclusão
                bool sucesso = response.Ok;  // Acessa o valor real do sucesso (true ou false)

                if (sucesso)  // Se a exclusão foi bem-sucedida (true)
                {
                    return Json(new { success = true, message = "Marca excluída com sucesso!" });
                }
                else
                {
                    return Json(new { success = false, message = "Falha ao excluir a marca." });
                }
            }
            else
            {
                // Se a marca estiver associada a um modelo, não pode ser excluída
                return Json(new { success = false, message = "Não é possível excluir a marca porque está associada a um modelo." });
            }
        }


    }
}

Concessionaria/Web/Pastelaria.Web/Controllers/ModeloController.cs
using Concessionaria.Web.Application.Marca;
using Concessionaria.Web.Application.Modelo;
using Concessionaria.Web.Application.Modelo.Model;
using Concessionaria.Web.Application.Motorizacao;
using Concessionaria.Web.Application.TipoCarroceria;
using Concessionaria.Web.Infra;
using System.Web.Mvc;

namespace Concessionaria.Web.Controllers
{
    public class ModeloController : BaseController
    {
        private readonly ModeloApplication _modeloApplication;
        private readonly MarcaApplication _marcaApplication;
        private readonly MotorizacaoApplication _motorizacaoApplication;
        private readonly TipoCarroceriaApplication _tipocarroceriaApplication;
        public ModeloController(ModeloApplication modeloApplication, MarcaApplication marcaApplication, MotorizacaoApplication motorizacaoApplication, TipoCarroceriaApplication tipocarroceriaApplication)
        {
            _modeloApplication = modeloApplication;
            _marcaApplication = marcaApplication;
            _motorizacaoApplication = motorizacaoApplication;
            _tipocarroceriaApplication = tipocarroceriaApplication;
        }

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ListarModelos()
        {
            var response = _modeloApplication.BuscarModelos();

            return View("_GridModelos", response.Content);
        }

        public ActionResult Adicionar()
        {
            var marcas = _marcaApplication.BuscarMarcas().Content;
            var motorizacoes = _motorizacaoApplication.BuscarTodasPotencias().Content;
            var tipos = _tipocarroceriaApplication.BuscarTiposCarroceria().Content;

            return View(new AdicionarModeloViewModel
            {
                Marcas = marcas,
                Motorizacoes = motorizacoes,
                TiposCarroceria = tipos
            });
        }

        [HttpPost]
        public ActionResult Adicionar(ModeloModel model)
        {
            if (ModelState.IsValid)
            {
                var response = _modeloApplication.Post(model);
                return Json(new { success = true, message = "Modelo adicionado com sucesso!" });
               
            }
            return Json(new { success = false, message = "Verifique os dados e preencher todos os campos" });
        }

        public ActionResult Editar(int id)
        {
            // Buscar o modelo pelo ID
            var modelo = _modeloApplication.BuscarModeloPorId(id).Content;
            if (modelo == null)
            {
                return HttpNotFound();
            }

            // Carregar as listas necessárias
            var marcas = _marcaApplication.BuscarMarcas().Content;
            var motorizacoes = _motorizacaoApplication.BuscarTodasPotencias().Content;
            var tipos = _tipocarroceriaApplication.BuscarTiposCarroceria().Content;

            // Retornar um ViewModel para a view
            var viewModel = new EditarModeloViewModel
            {
                Modelo = modelo,
                Marcas = marcas,
                Motorizacoes = motorizacoes,
                TiposCarroceria = tipos
            };

            return View(viewModel);
        }



        [HttpPost]
        public ActionResult Editar(ModeloModel model)
        {
            if (ModelState.IsValid)
            {
                var response = _modeloApplication.Put(model); // Método para atualizar
              
                {
                    return Json(new { success = true, message = "Modelo editado com sucesso!" });
                }
            }
            return Json(new { success = false, message = "Verifique os dados e preencher todos os campos" });
        }

        public ActionResult Excluir(int id)
        {

            // Valida se tem estoque está associada a algum modelo
            var validacaoResponse = _modeloApplication.ValidarModeloEstoque(id).Content;
            // Se o valor retornado for 0, significa que o modelo nao esta associado ao estoque

            if (validacaoResponse == false)
            {
                // Tenta excluir a marca
                var response = _modeloApplication.Delete(id); // Supondo que Delete retorne Response<bool>

                // Acessa o conteúdo da resposta para verificar o sucesso da exclusão
                bool sucesso = response.Ok;  // Acessa o valor real do sucesso (true ou false)

                if (sucesso)  // Se a exclusão foi bem-sucedida (true)
                {
                    return Json(new { success = true, message = "Modelo excluído com sucesso!" });
                }
                else
                {
                    return Json(new { success = false, message = "Falha ao excluir Modelo." });
                }
            }
            else
            {
                // Se a marca estiver associada a um modelo, não pode ser excluída
                return Json(new { success = false, message = "Não é possível excluir Modelo porque está associada a um Estoque." });
            }

        }

    }

}

Concessionaria/Web/Pastelaria.Web/Controllers/VendaController.cs
using Concessionaria.Web.Application.Cliente;
using Concessionaria.Web.Application.DetalhesVendas;
using Concessionaria.Web.Application.Email;
using Concessionaria.Web.Application.Estoque;
using Concessionaria.Web.Application.HistoricoVendas;
using Concessionaria.Web.Application.Venda;
using Concessionaria.Web.Application.Venda.Model;
using Concessionaria.Web.Helper;
using Concessionaria.Web.Infra;
using System;
using System.Web.Mvc;

namespace Concessionaria.Web.Controllers
{
    public class VendaController : BaseController
    {
        private readonly ClienteApplication _clienteApplication;
        private readonly EstoqueApplication _estoqueApplication;
        private readonly HistoricoApplication _historicoApplication;
        private readonly DetalhesVendaApplication _detalhevendaApplication;
        private readonly VendaApplication _vendaApplication;
        private readonly EmailApplication _emailApplication;
        private readonly EmailService _emailService;


        public VendaController(EmailService emailService, EmailApplication emailApplication, ClienteApplication clienteApplication, EstoqueApplication estoqueApplication, HistoricoApplication historicoApplication , DetalhesVendaApplication detalhevendaApplication, VendaApplication vendaApplication)
        {
            _estoqueApplication = estoqueApplication;
            _clienteApplication = clienteApplication;
            _historicoApplication = historicoApplication;
            _detalhevendaApplication = detalhevendaApplication;
            _vendaApplication = vendaApplication;
            _emailApplication = emailApplication;
            _emailService = emailService;
        }
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Adicionar()
        {
            var cliente = _clienteApplication.GetClientes().Content;
            var estoque = _estoqueApplication.BuscarEstoque().Content;
            return View(new AdicionarVendaViewModel
            {
                Clientes = cliente,
                Estoques = estoque,
            });
        }
        public ActionResult ListaVendas()
        {
            var response = _historicoApplication.BuscarHistoricoVendas();

            return View("_GridVendas",response.Content);
        }
        public ActionResult DetalhesVendas(int idVenda)
        {
            var response = _detalhevendaApplication.BuscarDetalhesPorId(idVenda);

            // Se não encontrar os detalhes da venda, redireciona ou exibe uma mensagem de erro
            if (response.Content == null)
            {
                return HttpNotFound();
            }

            return View("DetalhesVendas", response.Content);
        }

        [HttpPost]
        public ActionResult Post(VendaModel venda)
        {
            if (ModelState.IsValid)
            {
                var response = _vendaApplication.Post(venda);
                var idCliente = venda.Cliente.IdCliente;
                var emailCliente = _emailApplication.GetEmail(idCliente).Content;
                // Verifique se o cliente não é nulo e se há emails associados
                if (venda.Cliente != null && emailCliente != null)
                {
                    // Percorra todos os emails do cliente e envie os emails
                    foreach (var email in emailCliente)
                    {
                        try
                        {
                            // Envie o email usando EmailApplication
                            _emailService.EnviarEmail(email.Email, "Assunto do Email", "Corpo do Email");
                        }
                        catch (Exception ex)
                        {
                            // Registra o erro específico para cada e-mail falhado, se necessário.
                            Console.WriteLine($"Erro ao enviar e-mail para {email.Email}: {ex.Message}");
                        }
                    }
                }

                return Json(new { success = true, message = "Venda concluída com sucesso e emails enviados!" });
            }

            return Json(new { success = false, message = "Falha ao concluir venda" });
        }


    }
}

Concessionaria/Web/Pastelaria.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <style>
       * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: 'Poppins', sans-serif;
}

body {
    display: flex;
    min-height: 100vh;
    background-color: #e3e9f7;
}

nav {
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    background-color: #ffffff;
    height: 100vh;
    border-radius: 0px 18px 18px 0px;
    position: relative;
    transition: all 0.5s;
    min-width: 82px;
    z-index: 2;
}

#sidebar.open-sidebar {
    min-width: 15%;
    height:auto;
}

main {
    padding: 20px;
   
    z-index: 1;
    
}

#sidebar_content {
    padding: 12px;
}

#user {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-bottom: 24px;
}

#user_avatar {
    width: 49px;
    height: 44px;
    object-fit: cover;
    border-radius: 1px;
}

#user_infos {
    display: flex;
    flex-direction: column;
}

#user_infos span:last-child {
    color: #6b6b6b;
    font-size: 12px;
}
 
#side_items {
    display: flex;
    flex-direction: column;
    gap: 8px;
    list-style: none;
}

.side-item {
    border-radius: 8px;
    cursor: pointer;
    transition: background-color 0.3s;
}

.side-item.active {
    background-color: #007bff;
    
}

.side-item:hover {
    background-color: #ecf5f7; 
}

.side-item a {
    text-decoration: none;
    display: flex;
    align-items: center;
    padding: 14px; 
    color: #0a0a0a;
    transition: color 0.3s; 
}

.side-item.active a {
    color: #e3e9f7;
}

.side-item a i {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 16px; 
    height: 16px; 
    color: #007bff; 
}

.dropdown {
    display: none;
    flex-direction: column;
    gap: 8px;
    padding-left: 20px;
    list-style-type: none;
}

.dropdown.active {
    display: flex;
}

.dropdown-icon {
    margin-left: auto;
    transition: transform 0.3s ease;
    font-size: 12px;
    color: #007bff; 
}

.side-item.active .dropdown-icon {
    transform: rotate(180deg);
}

#logout {
    border-top: 1px solid #e3e9f7;
    padding: 12px;
}

#logout_btn {
    border: none;
    padding: 12px;
    font-size: 14px;
    display: flex;
    gap: 20px;
    align-items: center;
    border-radius: 8px;
    text-align: start;
    cursor: pointer;
    background-color: transparent;
}

#open_btn {
    position: absolute;
    top: 30px;
    right: -10px;
    background-color: #007bff;
    color: #e3e9f7;
    border-radius: 100%;
    width: 20px;
    height: 20px;
    border: none;
    cursor: pointer;
}

#open_btn_icon {
    transition: transform 0.3s ease;
}

.open-sidebar #open_btn_icon {
    transform: rotate(180deg);
}

.item-description {
    width: 0px;
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
    font-size: 14px;
    transition: width 0.6s;
    height: 0px;
}

#sidebar.open-sidebar .item-description {
    width: 150px;
    height: auto;
}

#sidebar.open-sidebar .side-item a {
    justify-content: flex-start;
    gap: 14px;
}

#item_list {
    margin-top: 20px;
}

.item {
    display: flex;
    justify-content: space-between;
    padding: 10px;
    background: white;
    border-radius: 5px;
    margin-bottom: 10px;
}

.item button {
    border: none;
    padding: 5px 10px;
    border-radius: 5px;
    cursor: pointer;
    background-color: #007bff;
    color: white;
}

#controls {
    display: flex;
    gap: 10px;
    margin-top: 20px;
}

#controls button {
    padding: 10px;
    border-radius: 5px;
    cursor: pointer;
    background-color: #4f46e5;
    color: white;
    border: none;
}

container body-content{
    background-color:rebeccapurple !important;
}

    </style>
</head>
<body>
    <nav id="sidebar">
        <div id="sidebar_content">
            <div id="user">
                <img src="~/IMG/carLogo.png" id="user_avatar" alt="Avatar">
                <p id="user_infos">
                   <span class="item-description" style="font-weight: bold; font-size: 1.2em;">Moises</span>

                </p>
            </div>
            <ul id="side_items">
                <li class="side-item active">
                    <a href="@Url.Action("Index", "Home")">
                        <i class="fa-solid fa-car" style="color: white;"></i>
                        <span class="item-description">Concessionaria</span>
                    </a>
                </li>
                <li class="side-item" id="user_item">
                    <a href="javascript:void(0);">
                        <i class="fa-solid fa-file-circle-plus"></i>
                        <span class="item-description">Cadastros</span>
                        <i class="fa-solid fa-chevron-down dropdown-icon"></i>
                    </a>
                    <ul class="dropdown" id="user_dropdown">
                        <li class="side-item"><a href="@Url.Action("Index", "Marca")">Marca</a></li>
                        <li class="side-item"><a href="@Url.Action("Index", "Modelo")">Modelo</a></li>
                        <li class="side-item"><a href="@Url.Action("Index", "Estoque")">Estoque</a></li>
                        <li class="side-item"><a href="@Url.Action("Index", "Cliente")">Cliente</a></li>
                        <li class="side-item"><a href="@Url.Action("Index", "Venda")">Venda</a></li>

                         <li class="side-item"><a href="@Url.Action("Index", "Asunto")">Modelo</a></li>
            


                    </ul>

                </li>
              
                <li class="side-item">
                    @*<a href="@Url.Action("Sobre", "Home")">*@
                    <a  hole="button" onclick="sobre.paginasobre()">
                        <i class="fa-solid fa-info-circle"></i>
                        <span class="item-description">Sobre</span>
                    </a>
                </li>
            </ul>
            <button id="open_btn">
                <i id="open_btn_icon" class="fa-solid fa-chevron-right"></i>
            </button>
        </div>
        <div id="logout">
            <button id="logout_btn">
                <i class="fa-solid fa-right-from-bracket"></i>
                <span class="item-description">Logout</span>
            </button>
        </div>
    </nav>
    <main class="container">
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>

        </div>
    </main>
    <script>
        document.getElementById('user_item').addEventListener('click', function() {
            document.getElementById('user_dropdown').classList.toggle('active');
        });
        document.getElementById('consultar_item').addEventListener('click', function() {
            document.getElementById('consultar_dropdown').classList.toggle('active');
        });
        document.getElementById('open_btn').addEventListener('click', function() {
            document.getElementById('sidebar').classList.toggle('open-sidebar');
        });
    </script>

    <script src="~/Lib/sobre/sobre.js"></script>

    <script>
sobre.init({
    urls: {
        paginasobre: '@(Url.Action("Sobre", "Home"))'
    }
});
    </script>

</body>
</html>