Concessionaria/Web/Pastelaria.Web/Controllers/ClienteController.cs
using Concessionaria.Web.Application.Cliente;
using Concessionaria.Web.Application.Cliente.Model;
using Concessionaria.Web.Application.Email;
using Concessionaria.Web.Application.Email.Model;
using Concessionaria.Web.Application.Endereco;
using Concessionaria.Web.Application.Endereco.Model;
using Concessionaria.Web.Application.Telefone;
using Concessionaria.Web.Application.Telefone.Model;
using Concessionaria.Web.Infra;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Concessionaria.Web.Controllers
{
    public class ClienteController : BaseController
    {
        private readonly ClienteApplication _clienteApplication;
        private readonly TelefoneApplication _telefoneApplication;
        private readonly EnderecoApplication _enderecoApplication;
        private readonly EmailApplication _emailApplication;

        public ClienteController(ClienteApplication clienteApplication, TelefoneApplication telefoneApplication, EnderecoApplication enderecoApplication, EmailApplication emailApplication)
        {
            _clienteApplication = clienteApplication;
            _telefoneApplication = telefoneApplication;
            _enderecoApplication = enderecoApplication;
            _emailApplication = emailApplication;
        }

        // Exibe a tela principal de clientes
        public ActionResult Index()
        {
            return View();
        }

        // Método para buscar cliente por CPF e retornar a view de edição/adicionar com os dados 
        public ActionResult BuscarClientePorCPF(string cpf = null)
        {
            if (string.IsNullOrEmpty(cpf))
            {
                // Se não houver CPF, retornamos um novo cliente vazio
                return View("_Form", new ClienteModel
                {
                    Telefones = new List<TelefoneModel>(),
                    Endereco = new List<EnderecoModel>(),
                    Email = new List<EmailModel>()
                });
            }

            // Buscar os dados do cliente pelo CPF
            var clienteResponse = _clienteApplication.GetClientePorCPF(cpf);
            if (!clienteResponse.Ok)
            {
                return Error("Falha ao buscar o cliente.");
            }
            var cliente = clienteResponse.Content;

            var telefonesResponse = _telefoneApplication.GetTelefone(cliente.IdCliente);
            var enderecoResponse = _enderecoApplication.GetEndereco(cliente.IdCliente);
            var emailResponse = _emailApplication.GetEmail(cliente.IdCliente);

            if (!telefonesResponse.Ok || !enderecoResponse.Ok || !emailResponse.Ok)
            {
                return Error("Falha ao buscar dados relacionados ao cliente.");
            }

            // Preenche o modelo com os dados do cliente e suas informações relacionadas
            cliente.Telefones = telefonesResponse.Content;
            cliente.Endereco = enderecoResponse.Content;
            cliente.Email = emailResponse.Content;

            return View("_Form", cliente);
        }

        // Tela de edição ou adição de cliente
        public ActionResult BuscarTelaEditarCliente(int? id = null)
        {
            if (!id.HasValue)
            {
                // Se não houver ID, retornamos um novo cliente vazio
                return View("_Form", new ClienteModel
                {
                    Telefones = new List<TelefoneModel>(),
                    Endereco = new List<EnderecoModel>(),
                    Email = new List<EmailModel>()
                });
            }

            // Se houver ID, buscamos os dados do cliente
            var clienteResponse = _clienteApplication.GetCliente(id.Value);
            if (!clienteResponse.Ok)
            {
                return Error("Falha ao buscar o cliente.");
            }

            var cliente = clienteResponse.Content;


            // Buscando os telefones, endereços e e-mails do cliente
            var telefonesResponse = _telefoneApplication.GetTelefone(cliente.IdCliente);
            var enderecoResponse = _enderecoApplication.GetEndereco(cliente.IdCliente);
            var emailResponse = _emailApplication.GetEmail(cliente.IdCliente);

            if (!telefonesResponse.Ok || !enderecoResponse.Ok || !emailResponse.Ok)
            {
                return Error("Falha ao buscar dados relacionados ao cliente.");
            }

            // Preenche o modelo com os dados do cliente e suas informações relacionadas
            cliente.Telefones = telefonesResponse.Content;
            cliente.Endereco = enderecoResponse.Content;
            cliente.Email = emailResponse.Content;

            return View("_Form", cliente);
        }

        // Salva ou atualiza o cliente
        public ActionResult Post(ClienteModel cliente)
        {
            var dataMinima = "01/01/0001 00:00:00";

            if ( cliente.Nome == null || cliente.CPF == null || cliente.DataNascimento.ToString() == dataMinima || cliente.Email == null || cliente.Telefones == null || cliente.Endereco == null)
            {
                return Json(new { success = false, message = "Preencher todos os campos." });
            }

            var response = _clienteApplication.Post(cliente);
            if (!response.Ok)
            {
                return Error("Falha ao inserir/atualizar cliente.");
            }

            return Json(new { success = true });
        }


        // Lista todos os clientes
        public ActionResult ListarClientes()
        {
            var response = _clienteApplication.GetClientes();
            if (!response.Ok)
                return Error("Falha ao buscar os clientes.");

            return View("_GridClientes", response.Content);
        }

        // Desativa um cliente
        public ActionResult Desativar(int id)
        {
            _clienteApplication.Delete(id);
            return Success();

        }
    }
}

Concessionaria/Web/Pastelaria.Web/Controllers/EmailController.cs
using Concessionaria.Web.Application.Email;
using Concessionaria.Web.Application.Email.Model;
using Concessionaria.Web.Infra;
using System.Web.Mvc;

namespace Concessionaria.Web.Controllers
{
    public class EmailController : BaseController
    {
        private readonly EmailApplication _emailApplication;

        public EmailController(EmailApplication emailApplication)
        {
            _emailApplication = emailApplication;
        }

        [HttpPost]
        public ActionResult LinhaGrid(EmailModel email)
        {
          
            return View("_LinhaGridEmail", email);
        }

        public ActionResult Deletar(int id)
        {
           
            _emailApplication.Delete(id);

          
            return Success();
        }
    }
}

Concessionaria/Web/Pastelaria.Web/Controllers/EnderecoController.cs
using Concessionaria.Web.Application.Endereco;
using Concessionaria.Web.Application.Endereco.Model;
using Concessionaria.Web.Infra;
using System.Web.Mvc;

namespace Concessionaria.Web.Controllers
{
    public class EnderecoController : BaseController
    {
        private readonly EnderecoApplication _enderecoApplication;
        public EnderecoController(EnderecoApplication enderecoApplication)
        {
            _enderecoApplication = enderecoApplication;
        }
        [HttpPost]
        public ActionResult LinhaGrid(EnderecoModel endereco)
        {
            // Retorna a view parcial "_LinhaGridEndereco" com o modelo de Endereço fornecido
            return View("_LinhaGridEndereco", endereco);
        }
        public ActionResult Deletar(int id)
        {
            // Chama o método de deletar da aplicação de Endereço
            _enderecoApplication.Delete(id);

            // Retorna um resultado de sucesso (presumivelmente definido em BaseController)
            return Success();
        }
    }
}

Concessionaria/Web/Pastelaria.Web/Controllers/TelefoneController.cs
using Concessionaria.Web.Application.Telefone;
using Concessionaria.Web.Application.Telefone.Model;
using Concessionaria.Web.Infra;
using System.Web.Mvc;

namespace Concessionaria.Web.Controllers
{
    public class TelefoneController : BaseController
    {
        private readonly TelefoneApplication _telefoneApplication;
        public TelefoneController(TelefoneApplication telefoneApplication)
        {
            _telefoneApplication = telefoneApplication;
        }

        [HttpPost]
        public ActionResult LinhaGrid(TelefoneModel telefone)
        {
          
            return View("_LinhaGridTelefone", telefone);
        }

      
        public ActionResult Deletar(int id)
        {
           
            _telefoneApplication.Delete(id);
           
            return Success(); 
        }
    }
}

Concessionaria/Web/Pastelaria.Web/Views/Cliente/Adicionar.cshtml
<div class="container">
    <h1>Cadastro de Cliente</h1>
    <form id="form-cliente">
        <!-- Informações Gerais -->
        <div class="section">
        
            <label for="cpf">CPF:</label>
            <input type="text" id="cpf" name="cpf" placeholder="Digite o CPF" required >

            <label for="nome">Nome Completo:</label>
            <input type="text" id="nome" name="nome" placeholder="Digite o nome completo" required>

            <label for="data-nascimento">Data de Nascimento:</label>
            <input type="date" id="data-nascimento" name="data-nascimento" required>
        </div>

        <!-- Dados de Contato -->
        <div class="section">
            <h2>Dados de Contato</h2>

            <!-- Email -->
            <div class="email-section">
                <label for="email">Email:</label>
                <input type="email" id="email" name="email" placeholder="Digite o e-mail" required>
                <button type="button" id="add-email">Adicionar Email</button>
                <div id="emails-list"></div>
            </div>

            <!-- Telefone -->
            <div class="telefone-section">
                <label for="telefone-ddd">Telefone:</label>
                <input type="text" id="telefone-ddd" name="telefone-ddd" placeholder="DDD" maxlength="2" required>
                <input type="text" id="telefone-numero" name="telefone-numero" placeholder="Número" maxlength="9" required>
                <input type="text" id="telefone-numero" name="telefone-numero" placeholder="Número" maxlength="9" required>
                <button type="button" id="add-telefone">Adicionar Telefone</button>
                <div id="telefones-list"></div>
            </div>

            <!-- Endereço -->
            <div class="endereco-section">
                <label for="cep">CEP:</label>
                <input type="text" id="cep" name="cep" placeholder="Digite o CEP" maxlength="8" required>

                <label for="rua">Rua:</label>
                <input type="text" id="rua" name="rua" placeholder="Digite a rua" required>

                <label for="numero">Número:</label>
                <input type="text" id="numero" name="numero" placeholder="Número" required>

                <label for="bairro">Bairro:</label>
                <input type="text" id="bairro" name="bairro" placeholder="Bairro" required>

                <label for="cidade">Cidade:</label>
                <input type="text" id="cidade" name="cidade" placeholder="Cidade" required>
                <button type="button" id="add-endereco">Adicionar Endereço</button>
                <div id="enderecos-list"></div>
            </div>
        </div>

        <button type="submit" id="submit-btn">Cadastrar</button>
    </form>
</div>

Concessionaria/Web/Pastelaria.Web/Views/Cliente/Index.cshtml
<div id="div-grid-clientes"></div> <!-- Aqui sera reenderizado Lista de cliente-->
<div id="div-add-cliente"></div> <!-- Aqui sera reenderizado tela de adicionar  cliente-->
<div id="div-editar-cliente"></div> <!-- Aqui sera reenderizado tela de editar  cliente-->
<!-- Adiciona o jQuery Mask Plugin -->


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<!-- Essa linha carrega a biblioteca jQuery versão 3.6.0 do CDN do Googleapis.
 O jQuery é uma biblioteca de JavaScript que simplifica a manipulação de documentos HTML,
  manipulação de eventos, animações e chamadas AJAX.-->

<script type="text/javascript" src="~/Lib/cliente/cliente.js?d=@DateTime.Now.Ticks"></script>  <!-- Aqui estou importando meu aquivo.js-->

<script>
    // chamar as views
    clientes.init({
        urls: {

            getGridClientes: '@Url.Action("ListarClientes", "Cliente")',
            buscarTelaAtualizarCliente: '@Url.Action("BuscarTelaEditarCliente", "Cliente")',
            buscarClientePorCPF: '@Url.Action("BuscarClientePorCPF", "Cliente")',
            post: '@(Url.Action("Post"))',
            linhaGridTelefone: '@Url.Action("LinhaGrid", "Telefone")',
            linhaGridEndereco: '@Url.Action("LinhaGrid", "Endereco")',
            linhaGridEmail: '@Url.Action("LinhaGrid", "Email")',
            deletarTelefone: '@Url.Action("Deletar", "Telefone")',
            deletarEndereco: '@Url.Action("Deletar", "Endereco")',
            deletarEmail: '@Url.Action("Deletar", "Email")',
            deletarCliente: '@Url.Action("Desativar", "Cliente")'

        }
      });

</script>

Concessionaria/Web/Pastelaria.Web/Views/Cliente/_Form.cshtml
@{
    Layout = null;
}

@using System.Linq
@model Concessionaria.Web.Application.Cliente.Model.ClienteModel

<div id="div-atualizar-usuario">
    <br>
    <div>
        <h4>@(Model.IdCliente != 0 ? "Editar Cliente" : "Adicionar Cliente")</h4>
    </div>
    <div>
        <button class="btn btn-primary float-right" style="margin-left: 10px;" onclick="clientes.buscarPorCPF()">
            Buscar
        </button>
        <input type="text" class="search-input float-right" id="searchInputCPF" placeholder="Buscar CPF ...">
    </div>
    <br>
    <div id="formCliente">
        <div class="row">
            <input type="hidden" name="IdCliente" value="@Model.IdCliente" />
            <div class="col-sm-3 mb-2">
                <label for="cpf" class="sr-only">CPF</label>
                <input type="text" class="form-control cpf" id="cpf" placeholder="CPF" value="@Model.CPF" name="CPF">
            </div>
            <div class="col-sm-4 mb-2">
                <label for="nome" class="sr-only">Nome</label>
                <input type="text" class="form-control nome" id="nome" placeholder="Nome" value="@Model.Nome" name="Nome">
            </div>
            <div class="col-sm-3 mb-2">
             <label for="datanascimento" class="sr-only">
                Data de Nascimento</label>
             <input type="date" class="form-control datanascimento" id="datanascimento" placeholder="Data de Nascimento" value="@Model.DataNascimento.ToString("yyyy-MM-dd")" name="DataNascimento">
             </div>
        </div>
    </div>
    <br /><br />
    <div>
        <h5>
            Telefones
            <a onclick="clientes.buscarTelaAdicionarTelefone()" class="btn btn-success btn-sm float-right" title="Adicionar Novo Telefone">
                <i class="fas fa-plus-circle"></i>
            </a>
        </h5>
        <div id="formTelefone" style="display: none">@Html.Partial("~/Views/Telefone/AdicionarTelefone.cshtml")</div>
    </div>
    <div id="div-grid-telefone">
        @Html.Partial("~/Views/Telefone/_GridTelefones.cshtml", Model.Telefones)
    </div>
    <hr />
    <br /><br />
    <div>
        <h5>
            Endereços
            <a onclick="clientes.buscarTelaAdicionarEndereco()" class="btn btn-success btn-sm float-right" title="Adicionar Novo Endereço">
                <i class="fas fa-plus-circle"></i>
            </a>
        </h5>
        <div id="formEndereco" style="display: none">@Html.Partial("~/Views/Endereco/AdicionarEndereco.cshtml")</div>
    </div>
    <div id="div-grid-endereco">
        @Html.Partial("~/Views/Endereco/_GridEnderecos.cshtml", Model.Endereco)
    </div>
    <hr />
    <br /><br />
    <div>
        <h5>
            Email
            <a onclick="clientes.buscarTelaAdicionarEmail()" class="btn btn-success btn-sm float-right">
                <i class="fas fa-plus-circle"></i>
            </a>
        </h5>
        <div id="formEmail" style="display: none">@Html.Partial("~/Views/Email/AdicionarEmail.cshtml")</div>
    </div>
    <div id="div-grid-email">
        @Html.Partial("~/Views/Email/_GridEmail.cshtml", Model.Email)
    </div>
    <hr />
    <br /><br />
    <a onclick="location.reload()" class="btn btn-warning btn-sm" title="cancelar e voltar para lista de clientes">CANCELAR</a>
    <button type="button" class="btn btn-success btn-sm" title="salvar cliente" onclick="clientes.salvar()">
        SALVAR
    </button>
</div>

Concessionaria/Web/Pastelaria.Web/Views/Cliente/_GridClientes.cshtml
@{
    Layout = null;
}
@using System.Linq
@model IEnumerable<Concessionaria.Web.Application.Cliente.Model.ClienteModel>

<div id="btnAddAdicionarUsuario">
    <a class="btn btn-success float-right" onclick="clientes.buscarTelaAtualizarCliente()">
        Adicionar novo Cliente
    </a>
</div>


<h2 id="tituloUsuarios" class="text-center">Clientes</h2>

<table id="clientesTable" class="table table-striped">
    <thead>
        <tr>
            <th>Usuário</th>
            <th>Email</th>
            <th>Data Nascimento</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Any())
        {
            foreach (var cliente in Model)
            {
                <tr class="clienteRow">
                    <td data-label="Usuário">@cliente.CPF</td>
                    <td data-label="Email">@cliente.Nome</td>
                    <td data-label="DataNascimento">@cliente.DataNascimento.ToString("dd/MM/yyyy")</td>
                    <td>
                        <a class="btn btn-primary btn-sm" onclick="clientes.buscarTelaAtualizarCliente(@cliente.IdCliente)">
                            <i class="fas fa-edit"></i>
                        </a>
                        <a class="btn btn-danger btn-sm" onclick="clientes.deletarCliente(@cliente.IdCliente)" title="Excluir usuário">
                            <i class="fas fa-trash-alt"></i>
                        </a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>
<div id="paginationControlsClientes" class="text-center">
    <button id="prevPageClientes" class="btn btn-secondary" disabled>Anterior</button>
    <span id="pageInfoClientes"></span>
    <button id="nextPageClientes" class="btn btn-secondary">Próximo</button>
</div>
<script>
    $(document).ready(function () {
        const rowsPerPage = 5; // Número de linhas por página
        let currentPageClientes = 1; // Página inicial para Clientes

        function showPage(page, tableSelector, rowSelector, pageInfoSelector, prevButtonSelector, nextButtonSelector) {
            const rows = $(tableSelector + " tbody " + rowSelector);
            const totalRows = rows.length;
            const totalPages = Math.ceil(totalRows / rowsPerPage);

            // Calculando os índices das linhas a serem exibidas
            const startIndex = (page - 1) * rowsPerPage;
            const endIndex = startIndex + rowsPerPage;

            // Ocultando todas as linhas
            rows.hide();

            // Mostrando as linhas da página atual
            rows.slice(startIndex, endIndex).show();

            // Atualizando as informações de paginação
            $(pageInfoSelector).text(`Página ${page} de ${totalPages}`);

            // Desabilitar ou habilitar os botões "Anterior" e "Próximo"
            $(prevButtonSelector).prop("disabled", page === 1);
            $(nextButtonSelector).prop("disabled", page === totalPages);
        }

        function initializePagination(tableSelector, rowSelector, pageInfoSelector, prevButtonSelector, nextButtonSelector) {
            // Inicializa a tabela com a primeira página
            showPage(currentPageClientes, tableSelector, rowSelector, pageInfoSelector, prevButtonSelector, nextButtonSelector);

            // Navegação entre as páginas
            $(prevButtonSelector).click(function () {
                if (currentPageClientes > 1) {
                    currentPageClientes--;
                    showPage(currentPageClientes, tableSelector, rowSelector, pageInfoSelector, prevButtonSelector, nextButtonSelector);
                }
            });

            $(nextButtonSelector).click(function () {
                const rows = $(tableSelector + " tbody " + rowSelector);
                const totalRows = rows.length;
                const totalPages = Math.ceil(totalRows / rowsPerPage);
                if (currentPageClientes < totalPages) {
                    currentPageClientes++;
                    showPage(currentPageClientes, tableSelector, rowSelector, pageInfoSelector, prevButtonSelector, nextButtonSelector);
                }
            });
        }

        // Inicializa a paginação para a tabela de Clientes
        initializePagination("#clientesTable", ".clienteRow", "#pageInfoClientes", "#prevPageClientes", "#nextPageClientes");
    });
</script>